services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "Spring12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - shop-network
    volumes:
      - sqlserver-data:/var/opt/mssql

networks:
  shop-network:

volumes:
  sqlserver-data:
